name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: ${{ secrets.YOUR_CLUSTER_NAME }}
          location: ${{ secrets.YOUR_CLUSTER_LOCATION }} # zona o región, ej. us-central1
          project_id: ${{secrets.YOUR_PROJECT_ID}}

      - name: Deploy to Kubernetes
        run: |
          gcloud builds submit --tag gcr.io/unlucoin2025v3/react-ws-app
          gcloud run deploy react-ws-app --image gcr.io/unlucoin2025v3/react-ws-app --platform managed --allow-unauthenticated --port 8080 --region us-east1